// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SLS-M5-Template

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2Label = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2Label, 0);
    lv_obj_set_y(ui_Screen2Label, -100);
    lv_obj_set_align(ui_Screen2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2Label, "Screen 2");

}
