// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SLS-M5-Template-Master

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SLS_Function_1(lv_event_t * e);
void SLS_Function_2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
